[package]
name = "primitives"
version = { workspace = true }
edition = { workspace = true }

[dependencies]
typeshare = { workspace = true }
serde = { workspace = true }
chrono = { workspace = true }
num-bigint = { workspace = true }
num-traits = { workspace = true }
