[postgres]
url = "postgres://username:password@localhost/api"

[redis]
url = "redis://default:@localhost:6379"

[coingecko.key]
secret = ""

[fiat]
timeout = 3

[moonpay]
[moonpay.key]
public = ""
secret = ""

[transak]
[transak.key]
public = ""

[mercuryo]
[mercuryo.key]
public = ""

[ramp]
[ramp.key]
public = ""

[pricer]
timer = 60

[plausible]
url = "https://plausible.gemwallet.com"

[name]
[name.ens]
url = "https://eth.llamarpc.com"

[name.ud]
url = "https://api.unstoppabledomains.com"

[name.ud.key]
secret = ""

[name.sns]
url = "https://sns-sdk-proxy.bonfida.workers.dev"

[name.ton]
url = "https://tonapi.io"

[name.eths]
url = "https://api.eths.center"

[name.spaceid]
url = "https://api.prd.space.id"

[metrics]
path = "/metrics"

[assets]
url = "https://raw.githubusercontent.com/gemwalletcom/assets/master"

[chains.binance]
url = "https://dex.binance.org"
api = "https://api.binance.org"

[chains.solana]
url = "https://solana-mainnet.rpc.extrnode.com"

[chains.ethereum]
url = "https://eth.llamarpc.com"

[chains.smartchain]
url = "https://binance.llamarpc.com"

[parser]
chain = ""
timeout = 1

[pusher]
url = ""

[pusher.ios]
topic = ""