[postgres]
url = "postgres://username:password@localhost/api"

[redis]
url = "redis://default:@localhost:6379"

[coingecko.key]
secret = ""

[fiat]
timeout = 3

[moonpay]
[moonpay.key]
public = ""
secret = ""

[transak]
[transak.key]
public = ""

[mercuryo]
[mercuryo.key]
public = ""
secret = ""

[ramp]
[ramp.key]
public = ""

[pricer]
timer = 60

[name]
[name.ens]
url = "https://eth.llamarpc.com"

[name.ud]
url = "https://api.unstoppabledomains.com"

[name.ud.key]
secret = ""

[name.sns]
url = "https://sns-sdk-proxy.bonfida.workers.dev"

[name.ton]
url = "https://tonapi.io"

[name.eths]
url = "https://api.eths.center"

[name.spaceid]
url = "https://api.prd.space.id"

[name.did]
url = "https://indexer-basic.did.id"

[name.suins]
url = "https://suins-rpc.mainnet.sui.io"

[metrics]
path = "/metrics"

[assets]
url = "https://raw.githubusercontent.com/gemwalletcom/assets/master"

[chains.binance]
url = "https://dex.binance.org"
api = "https://api.binance.org"

[chains.solana]
url = "https://api.mainnet-beta.solana.com"

[chains.ethereum]
url = "https://eth.llamarpc.com"

[chains.smartchain]
url = "https://binance.llamarpc.com"

[chains.polygon]
url = "https://polygon.llamarpc.com"

[chains.optimism]
url = "https://optimism.llamarpc.com"

[chains.arbitrum]
url = "https://arbitrum.llamarpc.com"

[chains.base]
url = "https://base-mainnet.public.blastapi.io"

[chains.opbnb]
url = "https://opbnb-mainnet-rpc.bnbchain.org"

[chains.avalanchec]
url = "https://api.avax.network/ext/bc/C/rpc"

[chains.fantom]
url = "https://fantom.publicnode.com"

[chains.gnosis]
url = "https://gnosis.publicnode.com"

[chains.ton]
url = "https://toncenter.com"

[chains.cosmos]
url = "https://cosmos-rest.publicnode.com"

[chains.osmosis]
url = "https://osmosis-rest.publicnode.com"

[chains.thorchain]
url = "https://thornode.ninerealms.com"

[chains.tron]
url = "https://api.trongrid.io"

[chains.xrp]
url = "https://s1.ripple.com:51234/"

[chains.aptos]
url = "https://fullnode.mainnet.aptoslabs.com"

[chains.sui]
url = "https://sui-rpc.publicnode.com"

[chains.bitcoin]
url = ""

[chains.litecoin]
url = ""

[chains.doge]
url = ""

[swap.oneinch]
url = "https://api.1inch.dev"
key = ""

[swap.oneinch.fee]
percent = 0.0
address = ""

[swap.jupiter]
url = "https://quote-api.jup.ag"
key = ""

[swap.jupiter.fee]
percent = 0.0
address = ""

[parser]
retry = 1
timeout = 1000 # ms
chains = [
    "ethereum",
    "binance",
    "smartchain",
    "arbitrum",
    "ton",
    "avalanchec",
    "base",
    "opbnb",
    "optimism",
    "polygon",
    "solana",
    "cosmos",
    "osmosis",
    "thorchain",
    "tron",
    "ripple",
    "aptos",
    "sui",
    "bitcoin",
    "doge",
    "fantom",
    "gnosis",
]

[pusher]
url = ""

[pusher.ios]
topic = ""

[deamon]
service = ""