appstore:
  refresh_interval_ms: 86400
  timeout_ms: 500
  keys:
    - crypto wallet
    - ton wallet
    - gem wallet
  apps:
    - name: Gem
      id: 6448712670
      package_id: com.gemwallet.android

  languages:
    - country: United States
      country_code: us
      language_code: en
    - country: United Kingdom
      country_code: gb
      language_code: en

googleplay:
  url: http://localhost:3000
  refresh_interval_ms: 86400
  timeout_ms: 500
