appstore:
  refresh_interval_ms: 86400
  timeout_ms: 500
  keys:
    - crypto wallet
  apps:
    - id: 6448712670
      name: Gem
  languages:
    - name: United States
      code: us
    - name: United Kingdom
      code: gb
