[swift]
prefix = ''

[swift.type_mappings]
"UInt32" = "UInt64"
"Int32" = "Int"
"BigInt" = "BigInt"
"NaiveDateTime" = "Date"

[kotlin.type_mappings]
"Date" = "Long"
"UInt32" = "Long"
"UInt64" = "Long"
"Int64" = "Long"
"NaiveDateTime" = "Long"