[package]
name = "ns_address_codec"
version = { workspace = true }
edition = { workspace = true }

[dependencies]

hex = { workspace = true }
bech32 = { workspace = true }
bs58 = { workspace = true }
base64 = { workspace = true }
ton_smart_contract_address = "0.0.4"