[package]
name = "settings"
version = { workspace = true }
edition = { workspace = true }

[dependencies]
typeshare = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
config = { workspace = true }