[package]
name = "setup"
edition = { workspace = true }
version = { workspace = true }

[dependencies]
tokio = { workspace = true }
storage = { path = "../storage" }
settings = { path = "../settings" }
primitives = { path = "../primitives" }
